services:
  - type: web
    name: shilaabo-car-hire-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
    autoDeploy: true
