services:
  - type: web
    name: shilaabo-car-hire
    env: node
    buildCommand: |
      # Install backend dependencies
      cd backend && npm install
      cd ..
      
      # Install frontend dependencies and build
      npm install
      npm run build
      
      # Copy dist to backend and verify
      mkdir -p backend/dist
      cp -r dist/* backend/dist/
      ls -la backend/dist
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://mohamedabukar412:IgA3vUwamvfD5Y9Z@cluster1.0c3ka.mongodb.net/?retryWrites=true&w=majority
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://shilaabo-tour-and-car-hire-1.onrender.com/api
    healthCheckPath: /api/health
    autoDeploy: true
