services:
  - type: web
    name: shilaabo-car-hire
    env: node
    buildCommand: |
      npm install
      npm run build
      cp -r dist backend/
      cd backend
      npm install
    startCommand: node backend/server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 8080
      - key: VITE_API_URL
        value: https://shilaabo-tour-and-car-hire-1.onrender.com/api
    autoDeploy: true
