services:
  - type: web
    name: shilaabo-car-hire
    env: node
    buildCommand: |
      cd backend && npm install
      cd ..
      npm install
      npm run build
      cp -r dist backend/
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://mohamedabukar412:IgA3vUwamvfD5Y9Z@cluster1.0c3ka.mongodb.net/?retryWrites=true&w=majority
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://shilaabo-tour-and-car-hire-1.onrender.com/api
    healthCheckPath: /api/health
    autoDeploy: true
